"""Baseline schema.

Stamps the schema as it stood at the end of the recorder/QC/storage/export
build. On a database that predates Alembic, run `alembic stamp 0001_baseline`
once instead of upgrading, so this migration is not replayed over live tables.


Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-02 08:35:46.937713
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('script', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('phonetic_tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_lang'), ['lang'], unique=False)
        batch_op.create_index('ix_prompts_lang_active', ['lang', 'active'], unique=False)

    op.create_table('speakers',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('caste_ethnicity', sa.String(length=120), nullable=True),
    sa.Column('age_band', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('ward', sa.String(length=10), nullable=True),
    sa.Column('mother_tongue', sa.String(length=60), nullable=True),
    sa.Column('language_variety', sa.String(length=80), nullable=True),
    sa.Column('education', sa.String(length=60), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_records',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('speaker_id', sa.String(length=26), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('commercial_use', sa.Boolean(), nullable=False),
    sa.Column('spoken_clip_key', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('speaker_id', sa.String(length=26), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('device_hint', sa.String(length=300), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_speaker_id'), ['speaker_id'], unique=False)

    op.create_table('clips',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('session_id', sa.String(length=26), nullable=False),
    sa.Column('speaker_id', sa.String(length=26), nullable=False),
    sa.Column('prompt_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('object_key', sa.String(length=400), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('qc_status', sa.String(length=16), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('snr_db', sa.Float(), nullable=True),
    sa.Column('peak_dbfs', sa.Float(), nullable=True),
    sa.Column('rms_dbfs', sa.Float(), nullable=True),
    sa.Column('noise_floor_dbfs', sa.Float(), nullable=True),
    sa.Column('clipping_ratio', sa.Float(), nullable=True),
    sa.Column('lead_silence_ms', sa.Float(), nullable=True),
    sa.Column('trail_silence_ms', sa.Float(), nullable=True),
    sa.Column('qc_codes', sa.JSON(), nullable=True),
    sa.Column('qc_reasons', sa.JSON(), nullable=True),
    sa.Column('client_metrics', sa.JSON(), nullable=True),
    sa.Column('verify_status', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=80), nullable=True),
    sa.Column('tombstoned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clips_lang'), ['lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_prompt_id'), ['prompt_id'], unique=False)
        batch_op.create_index('ix_clips_qc', ['qc_status', 'lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_qc_status'), ['qc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_speaker_id'), ['speaker_id'], unique=False)
        batch_op.create_index('ix_clips_speaker_prompt', ['speaker_id', 'prompt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_tombstoned'), ['tombstoned'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_tombstoned'))
        batch_op.drop_index('ix_clips_speaker_prompt')
        batch_op.drop_index(batch_op.f('ix_clips_speaker_id'))
        batch_op.drop_index(batch_op.f('ix_clips_session_id'))
        batch_op.drop_index(batch_op.f('ix_clips_qc_status'))
        batch_op.drop_index('ix_clips_qc')
        batch_op.drop_index(batch_op.f('ix_clips_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_clips_lang'))

    op.drop_table('clips')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_speaker_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_speaker_id'))

    op.drop_table('consent_records')
    op.drop_table('speakers')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_prompts_lang_active')
        batch_op.drop_index(batch_op.f('ix_prompts_lang'))
        batch_op.drop_index(batch_op.f('ix_prompts_active'))

    op.drop_table('prompts')
    # ### end Alembic commands ###
