"""Review pass: append-only events, structured reject reasons, ASR pre-filter.

Adds columns to the existing `clips` table. This is the case `create_all()`
cannot handle -- it would leave the new columns missing and every insert would
fail at runtime with `no such column`.


Revision ID: 0002_review_pass
Revises: 0001_baseline
Create Date: 2026-09-02 08:42:45.845944
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0002_review_pass"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('clip_id', sa.String(length=26), nullable=False),
    sa.Column('reviewer', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_events_clip_id'), ['clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_reviewer'), ['reviewer'], unique=False)
        batch_op.create_index('ix_review_events_reviewer_created', ['reviewer', 'created_at'], unique=False)

    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.String(length=300), nullable=True))
        batch_op.add_column(
            sa.Column(
                "review_priority",
                sa.Integer(),
                nullable=False,
                # Existing rows predate the review queue; they start at 0.
                server_default="0",
            )
        )
        batch_op.add_column(sa.Column('asr_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('asr_cer', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('asr_model', sa.String(length=60), nullable=True))
        batch_op.create_index('ix_clips_review', ['verify_status', 'lang', 'tombstoned'], unique=False)
        batch_op.create_index(batch_op.f('ix_clips_review_priority'), ['review_priority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clips_review_priority'))
        batch_op.drop_index('ix_clips_review')
        batch_op.drop_column('asr_model')
        batch_op.drop_column('asr_cer')
        batch_op.drop_column('asr_text')
        batch_op.drop_column('review_priority')
        batch_op.drop_column('review_notes')
        batch_op.drop_column('reject_reason')

    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_index('ix_review_events_reviewer_created')
        batch_op.drop_index(batch_op.f('ix_review_events_reviewer'))
        batch_op.drop_index(batch_op.f('ix_review_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_review_events_clip_id'))

    op.drop_table('review_events')
    # ### end Alembic commands ###
